// SPDX-License-Identifier: MIT
// Generated by scripts/generate_language_catalog.ts; request choices stay identical on every host.
export const SUPPORTED_LANGUAGES: readonly { tag: string; name: string; nativeName: string }[] = [
  {
    tag: "af",
    name: "Afrikaans",
    nativeName: "Afrikaans",
  },
  {
    tag: "agq",
    name: "Aghem",
    nativeName: "Aghem",
  },
  {
    tag: "ain",
    name: "Ainu",
    nativeName: "アイヌ・イタㇰ",
  },
  {
    tag: "ak",
    name: "Akan",
    nativeName: "Akan",
  },
  {
    tag: "am",
    name: "Amharic",
    nativeName: "አማርኛ",
  },
  {
    tag: "apw",
    name: "Apache, Western",
    nativeName: "Nṉee biyátiʼ",
  },
  {
    tag: "ar",
    name: "Arabic",
    nativeName: "العربية",
  },
  {
    tag: "arn",
    name: "Mapuche",
    nativeName: "Mapudungun",
  },
  {
    tag: "as",
    name: "Assamese",
    nativeName: "অসমীয়া",
  },
  {
    tag: "asa",
    name: "Asu",
    nativeName: "Kipare",
  },
  {
    tag: "ast",
    name: "Asturian",
    nativeName: "asturianu",
  },
  {
    tag: "az",
    name: "Azerbaijani",
    nativeName: "azərbaycan",
  },
  {
    tag: "ba",
    name: "Bashkir",
    nativeName: "башҡорт",
  },
  {
    tag: "bas",
    name: "Basaa",
    nativeName: "Ɓàsàa",
  },
  {
    tag: "be",
    name: "Belarusian",
    nativeName: "беларуская",
  },
  {
    tag: "bem",
    name: "Bemba",
    nativeName: "Ichibemba",
  },
  {
    tag: "ber",
    name: "Amazigh",
    nativeName: "ⴰⵎⴰⵣⵉⵖ",
  },
  {
    tag: "bez",
    name: "Bena",
    nativeName: "Hibena",
  },
  {
    tag: "bg",
    name: "Bulgarian",
    nativeName: "български",
  },
  {
    tag: "bgc",
    name: "Haryanvi",
    nativeName: "हरियाणवी",
  },
  {
    tag: "bho",
    name: "Bhojpuri",
    nativeName: "भोजपुरी",
  },
  {
    tag: "blo",
    name: "Anii",
    nativeName: "anii kagɩja",
  },
  {
    tag: "bm",
    name: "Bambara",
    nativeName: "bamanakan",
  },
  {
    tag: "bn",
    name: "Bangla",
    nativeName: "বাংলা",
  },
  {
    tag: "bo",
    name: "Tibetan",
    nativeName: "བོད་སྐད་",
  },
  {
    tag: "br",
    name: "Breton",
    nativeName: "brezhoneg",
  },
  {
    tag: "brx",
    name: "Bodo",
    nativeName: "बरʼ",
  },
  {
    tag: "bs",
    name: "Bosnian",
    nativeName: "bosanski",
  },
  {
    tag: "bua",
    name: "Buriat",
    nativeName: "буряад",
  },
  {
    tag: "byn",
    name: "Blin",
    nativeName: "ብሊን",
  },
  {
    tag: "ca",
    name: "Catalan",
    nativeName: "català",
  },
  {
    tag: "ccp",
    name: "Chakma",
    nativeName: "𑄌𑄋𑄴𑄟𑄳𑄦",
  },
  {
    tag: "ce",
    name: "Chechen",
    nativeName: "нохчийн",
  },
  {
    tag: "ceb",
    name: "Cebuano",
    nativeName: "Cebuano",
  },
  {
    tag: "cgg",
    name: "Chiga",
    nativeName: "Rukiga",
  },
  {
    tag: "cho",
    name: "Choctaw",
    nativeName: "Chahta",
  },
  {
    tag: "chr",
    name: "Cherokee",
    nativeName: "ᏣᎳᎩ",
  },
  {
    tag: "cic",
    name: "Chickasaw",
    nativeName: "Chikashshanompaʼ",
  },
  {
    tag: "ckb",
    name: "Kurdish, Sorani",
    nativeName: "کوردیی ناوەندی",
  },
  {
    tag: "co",
    name: "Corsican",
    nativeName: "corsu",
  },
  {
    tag: "cs",
    name: "Czech",
    nativeName: "Čeština",
  },
  {
    tag: "cst",
    name: "Chochenyo",
    nativeName: "Chochenyo",
  },
  {
    tag: "csw",
    name: "Swampy Cree",
    nativeName: "ᓀᐦᐃᓇᐍᐏᐣ",
  },
  {
    tag: "cv",
    name: "Chuvash",
    nativeName: "чӑваш чӗлхи",
  },
  {
    tag: "cy",
    name: "Welsh",
    nativeName: "Cymraeg",
  },
  {
    tag: "da",
    name: "Danish",
    nativeName: "dansk",
  },
  {
    tag: "dav",
    name: "Taita",
    nativeName: "Kitaita",
  },
  {
    tag: "de",
    name: "German",
    nativeName: "Deutsch",
  },
  {
    tag: "dje",
    name: "Zarma",
    nativeName: "Zarmaciine",
  },
  {
    tag: "doi",
    name: "Dogri",
    nativeName: "डोगरी",
  },
  {
    tag: "dsb",
    name: "Lower Sorbian",
    nativeName: "dolnoserbšćina",
  },
  {
    tag: "dua",
    name: "Duala",
    nativeName: "duálá",
  },
  {
    tag: "dv",
    name: "Dhivehi",
    nativeName: "ދިވެހިބަސް",
  },
  {
    tag: "dyo",
    name: "Jola-Fonyi",
    nativeName: "joola",
  },
  {
    tag: "dz",
    name: "Dzongkha",
    nativeName: "རྫོང་ཁ་",
  },
  {
    tag: "ebu",
    name: "Embu",
    nativeName: "Kĩembu",
  },
  {
    tag: "ee",
    name: "Ewe",
    nativeName: "eʋegbe",
  },
  {
    tag: "el",
    name: "Greek",
    nativeName: "Ελληνικά",
  },
  {
    tag: "en",
    name: "English",
    nativeName: "English",
  },
  {
    tag: "en-GB",
    name: "English (UK)",
    nativeName: "English (UK)",
  },
  {
    tag: "en-US",
    name: "English (US)",
    nativeName: "English (US)",
  },
  {
    tag: "eo",
    name: "Esperanto",
    nativeName: "Esperanto",
  },
  {
    tag: "es",
    name: "Spanish",
    nativeName: "Español",
  },
  {
    tag: "es-419",
    name: "Spanish (Latin America)",
    nativeName: "Español (Latinoamérica)",
  },
  {
    tag: "et",
    name: "Estonian",
    nativeName: "eesti",
  },
  {
    tag: "eu",
    name: "Basque",
    nativeName: "euskara",
  },
  {
    tag: "ewo",
    name: "Ewondo",
    nativeName: "ewondo",
  },
  {
    tag: "fa",
    name: "Persian",
    nativeName: "فارسی",
  },
  {
    tag: "ff",
    name: "Fula",
    nativeName: "Pulaar",
  },
  {
    tag: "fi",
    name: "Finnish",
    nativeName: "suomi",
  },
  {
    tag: "fil",
    name: "Filipino",
    nativeName: "Filipino",
  },
  {
    tag: "fo",
    name: "Faroese",
    nativeName: "føroyskt",
  },
  {
    tag: "fr",
    name: "French",
    nativeName: "français",
  },
  {
    tag: "fur",
    name: "Friulian",
    nativeName: "furlan",
  },
  {
    tag: "fy",
    name: "Western Frisian",
    nativeName: "Frysk",
  },
  {
    tag: "ga",
    name: "Irish",
    nativeName: "Gaeilge",
  },
  {
    tag: "gaa",
    name: "Ga",
    nativeName: "Gã",
  },
  {
    tag: "gd",
    name: "Scottish Gaelic",
    nativeName: "Gàidhlig",
  },
  {
    tag: "gez",
    name: "Geez",
    nativeName: "ግዕዝኛ",
  },
  {
    tag: "gl",
    name: "Galician",
    nativeName: "galego",
  },
  {
    tag: "gn",
    name: "Guarani",
    nativeName: "avañe’ẽ",
  },
  {
    tag: "gsw",
    name: "Swiss German",
    nativeName: "Schwiizertüütsch",
  },
  {
    tag: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
  },
  {
    tag: "guz",
    name: "Gusii",
    nativeName: "Ekegusii",
  },
  {
    tag: "gv",
    name: "Manx",
    nativeName: "Gaelg",
  },
  {
    tag: "ha",
    name: "Hausa",
    nativeName: "Hausa",
  },
  {
    tag: "haw",
    name: "Hawaiian",
    nativeName: "ʻŌlelo Hawaiʻi",
  },
  {
    tag: "hch",
    name: "Wixárika",
    nativeName: "Wixárika",
  },
  {
    tag: "he",
    name: "Hebrew",
    nativeName: "עברית",
  },
  {
    tag: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
  },
  {
    tag: "hmn",
    name: "Hmong",
    nativeName: "𖬌𖬣𖬵",
  },
  {
    tag: "hr",
    name: "Croatian",
    nativeName: "Hrvatski",
  },
  {
    tag: "hsb",
    name: "Upper Sorbian",
    nativeName: "hornjoserbšćina",
  },
  {
    tag: "ht",
    name: "Haitian Creole",
    nativeName: "Kreyòl Ayisyen",
  },
  {
    tag: "hu",
    name: "Hungarian",
    nativeName: "magyar",
  },
  {
    tag: "hy",
    name: "Armenian",
    nativeName: "հայերեն",
  },
  {
    tag: "ia",
    name: "Interlingua",
    nativeName: "interlingua",
  },
  {
    tag: "id",
    name: "Indonesian",
    nativeName: "Indonesia",
  },
  {
    tag: "ie",
    name: "Interlingue",
    nativeName: "Interlingue",
  },
  {
    tag: "ig",
    name: "Igbo",
    nativeName: "Igbo",
  },
  {
    tag: "ii",
    name: "Liangshan Yi",
    nativeName: "ꆈꌠꉙ",
  },
  {
    tag: "inh",
    name: "Ingush",
    nativeName: "ГӀалгӀай мотт",
  },
  {
    tag: "io",
    name: "Ido",
    nativeName: "Ido",
  },
  {
    tag: "is",
    name: "Icelandic",
    nativeName: "íslenska",
  },
  {
    tag: "isc",
    name: "Iskonawa",
    nativeName: "Iskonawa",
  },
  {
    tag: "it",
    name: "Italian",
    nativeName: "Italiano",
  },
  {
    tag: "iu",
    name: "Inuktitut",
    nativeName: "ᐃᓄᒃᑎᑐᑦ",
  },
  {
    tag: "ja",
    name: "Japanese",
    nativeName: "日本語",
  },
  {
    tag: "jbo",
    name: "Lojban",
    nativeName: "la .lojban.",
  },
  {
    tag: "jgo",
    name: "Ngomba",
    nativeName: "Ndaꞌa",
  },
  {
    tag: "jmc",
    name: "Machame",
    nativeName: "Kimachame",
  },
  {
    tag: "jv",
    name: "Javanese",
    nativeName: "Jawa",
  },
  {
    tag: "ka",
    name: "Georgian",
    nativeName: "ქართული",
  },
  {
    tag: "kab",
    name: "Kabyle",
    nativeName: "Taqbaylit",
  },
  {
    tag: "kaj",
    name: "Jju",
    nativeName: "Kaje",
  },
  {
    tag: "kam",
    name: "Kamba",
    nativeName: "Kikamba",
  },
  {
    tag: "kcg",
    name: "Tyap",
    nativeName: "Katab",
  },
  {
    tag: "kde",
    name: "Makonde",
    nativeName: "Chimakonde",
  },
  {
    tag: "kea",
    name: "Kabuverdianu",
    nativeName: "kabuverdianu",
  },
  {
    tag: "kgp",
    name: "Kaingang",
    nativeName: "Kanhgág",
  },
  {
    tag: "khq",
    name: "Koyra Chiini",
    nativeName: "Koyra ciini",
  },
  {
    tag: "ki",
    name: "Kikuyu",
    nativeName: "Gikuyu",
  },
  {
    tag: "kk",
    name: "Kazakh",
    nativeName: "қазақ тілі",
  },
  {
    tag: "kkj",
    name: "Kako",
    nativeName: "kakɔ",
  },
  {
    tag: "kl",
    name: "Kalaallisut",
    nativeName: "kalaallisut",
  },
  {
    tag: "kln",
    name: "Kalenjin",
    nativeName: "Kalenjin",
  },
  {
    tag: "km",
    name: "Khmer",
    nativeName: "ខ្មែរ",
  },
  {
    tag: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
  },
  {
    tag: "ko",
    name: "Korean",
    nativeName: "한국어",
  },
  {
    tag: "kok",
    name: "Konkani",
    nativeName: "कोंकणी",
  },
  {
    tag: "kpe",
    name: "Kpelle",
    nativeName: "Kpɛlɛɛ",
  },
  {
    tag: "ks",
    name: "Kashmiri",
    nativeName: "کٲشُر",
  },
  {
    tag: "ksb",
    name: "Shambala",
    nativeName: "Kishambaa",
  },
  {
    tag: "ksf",
    name: "Bafia",
    nativeName: "rikpa",
  },
  {
    tag: "ksh",
    name: "Colognian",
    nativeName: "Kölsch",
  },
  {
    tag: "ku",
    name: "Kurdish",
    nativeName: "kurdî (kurmancî)",
  },
  {
    tag: "kw",
    name: "Cornish",
    nativeName: "kernewek",
  },
  {
    tag: "kxv",
    name: "Kuvi",
    nativeName: "kuvi",
  },
  {
    tag: "ky",
    name: "Kyrgyz",
    nativeName: "кыргызча",
  },
  {
    tag: "lag",
    name: "Langi",
    nativeName: "Kɨlaangi",
  },
  {
    tag: "lb",
    name: "Luxembourgish",
    nativeName: "Lëtzebuergesch",
  },
  {
    tag: "lg",
    name: "Ganda",
    nativeName: "Luganda",
  },
  {
    tag: "lij",
    name: "Ligurian",
    nativeName: "ligure",
  },
  {
    tag: "lkt",
    name: "Lakota",
    nativeName: "Lakȟólʼiyapi",
  },
  {
    tag: "lmo",
    name: "Lombard",
    nativeName: "Lombard",
  },
  {
    tag: "ln",
    name: "Lingala",
    nativeName: "lingála",
  },
  {
    tag: "lo",
    name: "Lao",
    nativeName: "ລາວ",
  },
  {
    tag: "lrc",
    name: "Northern Luri",
    nativeName: "لۊری شومالی",
  },
  {
    tag: "lt",
    name: "Lithuanian",
    nativeName: "lietuvių",
  },
  {
    tag: "lu",
    name: "Luba-Katanga",
    nativeName: "Tshiluba",
  },
  {
    tag: "luo",
    name: "Luo",
    nativeName: "Dholuo",
  },
  {
    tag: "lut",
    name: "Lushootseed",
    nativeName: "dxʷləšucid · txʷəlšucid · xʷəlšucid",
  },
  {
    tag: "luy",
    name: "Luyia",
    nativeName: "Luluhia",
  },
  {
    tag: "lv",
    name: "Latvian",
    nativeName: "latviešu",
  },
  {
    tag: "mai",
    name: "Maithili",
    nativeName: "मैथिली",
  },
  {
    tag: "mas",
    name: "Masai",
    nativeName: "Maa",
  },
  {
    tag: "mer",
    name: "Meru",
    nativeName: "Kĩmĩrũ",
  },
  {
    tag: "mfe",
    name: "Morisyen",
    nativeName: "kreol morisien",
  },
  {
    tag: "mg",
    name: "Malagasy",
    nativeName: "Malagasy",
  },
  {
    tag: "mgh",
    name: "Makhuwa-Meetto",
    nativeName: "Makua",
  },
  {
    tag: "mgo",
    name: "Metaʼ",
    nativeName: "metaʼ",
  },
  {
    tag: "mi",
    name: "Māori",
    nativeName: "Māori",
  },
  {
    tag: "mic",
    name: "Mi’kmaw",
    nativeName: "Lʼnuiʼsuti",
  },
  {
    tag: "mid",
    name: "Mandaic",
    nativeName: "ࡌࡀࡍࡃࡀࡉࡀ",
  },
  {
    tag: "mk",
    name: "Macedonian",
    nativeName: "македонски",
  },
  {
    tag: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
  },
  {
    tag: "mn",
    name: "Mongolian",
    nativeName: "монгол",
  },
  {
    tag: "mni",
    name: "Manipuri",
    nativeName: "মৈতৈলোন্",
  },
  {
    tag: "moh",
    name: "Mohawk",
    nativeName: "Kanienʼkéha",
  },
  {
    tag: "mr",
    name: "Marathi",
    nativeName: "मराठी",
  },
  {
    tag: "ms",
    name: "Malay",
    nativeName: "Bahasa Melayu",
  },
  {
    tag: "mt",
    name: "Maltese",
    nativeName: "Malti",
  },
  {
    tag: "mua",
    name: "Mundang",
    nativeName: "MUNDAŊ",
  },
  {
    tag: "mus",
    name: "Mvskoke",
    nativeName: "Mvskoke",
  },
  {
    tag: "my",
    name: "Burmese",
    nativeName: "မြန်မာ",
  },
  {
    tag: "myv",
    name: "Erzya",
    nativeName: "эрзянь кель",
  },
  {
    tag: "mzn",
    name: "Mazanderani",
    nativeName: "مازرونی",
  },
  {
    tag: "naq",
    name: "Nama",
    nativeName: "Khoekhoegowab",
  },
  {
    tag: "nb",
    name: "Norwegian Bokmål",
    nativeName: "norsk bokmål",
  },
  {
    tag: "nd",
    name: "North Ndebele",
    nativeName: "isiNdebele",
  },
  {
    tag: "nds",
    name: "Low German",
    nativeName: "Neddersass’sch",
  },
  {
    tag: "ne",
    name: "Nepali",
    nativeName: "नेपाली",
  },
  {
    tag: "nez",
    name: "Nez Perce",
    nativeName: "nimipuutímt",
  },
  {
    tag: "nl",
    name: "Dutch",
    nativeName: "Nederlands",
  },
  {
    tag: "nn",
    name: "Norwegian Nynorsk",
    nativeName: "norsk nynorsk",
  },
  {
    tag: "nnh",
    name: "Ngiemboon",
    nativeName: "Shwóŋò ngiembɔɔn",
  },
  {
    tag: "nnp",
    name: "Wancho",
    nativeName: "𞋒𞋀𞋉𞋃𞋕",
  },
  {
    tag: "no",
    name: "Norwegian",
    nativeName: "norsk",
  },
  {
    tag: "nqo",
    name: "N’Ko",
    nativeName: "ߒߞߏ",
  },
  {
    tag: "nso",
    name: "Northern Sotho",
    nativeName: "Sesotho sa Leboa",
  },
  {
    tag: "nus",
    name: "Nuer",
    nativeName: "Thok Nath",
  },
  {
    tag: "nv",
    name: "Navajo",
    nativeName: "Diné Bizaad",
  },
  {
    tag: "ny",
    name: "Nyanja",
    nativeName: "Nyanja",
  },
  {
    tag: "nyn",
    name: "Nyankole",
    nativeName: "Runyankore",
  },
  {
    tag: "oc",
    name: "Occitan",
    nativeName: "occitan",
  },
  {
    tag: "om",
    name: "Oromo",
    nativeName: "Oromoo",
  },
  {
    tag: "or",
    name: "Odia",
    nativeName: "ଓଡ଼ିଆ",
  },
  {
    tag: "os",
    name: "Ossetic",
    nativeName: "ирон",
  },
  {
    tag: "osa",
    name: "Osage",
    nativeName: "𐓏𐓘𐓻𐓘𐓻𐓟",
  },
  {
    tag: "pa",
    name: "Punjabi",
    nativeName: "ਪੰਜਾਬੀ",
  },
  {
    tag: "pcm",
    name: "Nigerian Pidgin",
    nativeName: "Naijíriá Píjin",
  },
  {
    tag: "pl",
    name: "Polish",
    nativeName: "polski",
  },
  {
    tag: "pms",
    name: "Piedmontese",
    nativeName: "piemontèis",
  },
  {
    tag: "pqm",
    name: "Wolastoqey",
    nativeName: "Wolastoqey",
  },
  {
    tag: "prg",
    name: "Prussian",
    nativeName: "prūsiskan",
  },
  {
    tag: "ps",
    name: "Pashto",
    nativeName: "پښتو",
  },
  {
    tag: "pt",
    name: "Portuguese",
    nativeName: "Português",
  },
  {
    tag: "pt-BR",
    name: "Portuguese (Brazil)",
    nativeName: "Português (Brasil)",
  },
  {
    tag: "pt-PT",
    name: "Portuguese (Portugal)",
    nativeName: "Português (Portugal)",
  },
  {
    tag: "qu",
    name: "Quechua",
    nativeName: "Runasimi",
  },
  {
    tag: "raj",
    name: "Rajasthani",
    nativeName: "राजस्थानी",
  },
  {
    tag: "rej",
    name: "Rejang",
    nativeName: "Baso Hejang",
  },
  {
    tag: "rhg",
    name: "Rohingya",
    nativeName: "𐴌𐴗𐴥𐴝𐴙𐴚𐴒𐴙𐴝",
  },
  {
    tag: "rm",
    name: "Romansh",
    nativeName: "rumantsch",
  },
  {
    tag: "rn",
    name: "Rundi",
    nativeName: "Ikirundi",
  },
  {
    tag: "ro",
    name: "Romanian",
    nativeName: "română",
  },
  {
    tag: "rof",
    name: "Rombo",
    nativeName: "Kihorombo",
  },
  {
    tag: "ru",
    name: "Russian",
    nativeName: "Русский",
  },
  {
    tag: "rw",
    name: "Kinyarwanda",
    nativeName: "Ikinyarwanda",
  },
  {
    tag: "rwk",
    name: "Rwa",
    nativeName: "Kiruwa",
  },
  {
    tag: "sa",
    name: "Sanskrit",
    nativeName: "संस्कृत भाषा",
  },
  {
    tag: "sah",
    name: "Sakha",
    nativeName: "саха тыла",
  },
  {
    tag: "saq",
    name: "Samburu",
    nativeName: "Kisampur",
  },
  {
    tag: "sat",
    name: "Santali",
    nativeName: "ᱥᱟᱱᱛᱟᱲᱤ",
  },
  {
    tag: "sbp",
    name: "Sangu",
    nativeName: "Ishisangu",
  },
  {
    tag: "sc",
    name: "Sardinian",
    nativeName: "sardu",
  },
  {
    tag: "scn",
    name: "Sicilian",
    nativeName: "sicilianu",
  },
  {
    tag: "sd",
    name: "Sindhi",
    nativeName: "سنڌي",
  },
  {
    tag: "se",
    name: "North Sámi",
    nativeName: "davvisámegiella",
  },
  {
    tag: "seh",
    name: "Sena",
    nativeName: "sena",
  },
  {
    tag: "ses",
    name: "Koyraboro Senni",
    nativeName: "Koyraboro senni",
  },
  {
    tag: "sg",
    name: "Sango",
    nativeName: "Sängö",
  },
  {
    tag: "shi",
    name: "Tachelhit",
    nativeName: "ⵜⴰⵛⵍⵃⵉⵜ",
  },
  {
    tag: "shn",
    name: "Shan",
    nativeName: "တႆး",
  },
  {
    tag: "shp",
    name: "Shipibo-Konibo",
    nativeName: "Shipibo-Konibo",
  },
  {
    tag: "si",
    name: "Sinhala",
    nativeName: "සිංහල",
  },
  {
    tag: "sjd",
    name: "Kildin Sámi",
    nativeName: "Кӣллт са̄мь кӣлл",
  },
  {
    tag: "sje",
    name: "Pite Sámi",
    nativeName: "Bidumsámegiella",
  },
  {
    tag: "sju",
    name: "Ume Sámi",
    nativeName: "Ubmejesámiengiälla",
  },
  {
    tag: "sk",
    name: "Slovak",
    nativeName: "Slovenčina",
  },
  {
    tag: "sl",
    name: "Slovenian",
    nativeName: "slovenščina",
  },
  {
    tag: "sm",
    name: "Samoan",
    nativeName: "Gagana faʻa Sāmoa",
  },
  {
    tag: "smn",
    name: "Inari Sami",
    nativeName: "anarâškielâ",
  },
  {
    tag: "sn",
    name: "Shona",
    nativeName: "chiShona",
  },
  {
    tag: "so",
    name: "Somali",
    nativeName: "Soomaali",
  },
  {
    tag: "sq",
    name: "Albanian",
    nativeName: "shqip",
  },
  {
    tag: "sr",
    name: "Serbian",
    nativeName: "српски",
  },
  {
    tag: "ss",
    name: "Swati",
    nativeName: "siSwati",
  },
  {
    tag: "st",
    name: "Southern Sotho",
    nativeName: "Sesotho",
  },
  {
    tag: "su",
    name: "Sundanese",
    nativeName: "Basa Sunda",
  },
  {
    tag: "sv",
    name: "Swedish",
    nativeName: "Svenska",
  },
  {
    tag: "sw",
    name: "Swahili",
    nativeName: "Kiswahili",
  },
  {
    tag: "syr",
    name: "Assyrian",
    nativeName: "ܣܘܪܝܝܐ",
  },
  {
    tag: "szl",
    name: "Silesian",
    nativeName: "ślōnski",
  },
  {
    tag: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
  },
  {
    tag: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
  },
  {
    tag: "teo",
    name: "Teso",
    nativeName: "Kiteso",
  },
  {
    tag: "tg",
    name: "Tajik",
    nativeName: "тоҷикӣ",
  },
  {
    tag: "th",
    name: "Thai",
    nativeName: "ไทย",
  },
  {
    tag: "ti",
    name: "Tigrinya",
    nativeName: "ትግርኛ",
  },
  {
    tag: "tig",
    name: "Tigre",
    nativeName: "ትግረ",
  },
  {
    tag: "tk",
    name: "Turkmen",
    nativeName: "Türkmen dili",
  },
  {
    tag: "tn",
    name: "Tswana",
    nativeName: "Setswana",
  },
  {
    tag: "to",
    name: "Tongan",
    nativeName: "lea fakatonga",
  },
  {
    tag: "tok",
    name: "Toki Pona",
    nativeName: "toki pona",
  },
  {
    tag: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
  },
  {
    tag: "trv",
    name: "Taroko",
    nativeName: "patas Taroko",
  },
  {
    tag: "ts",
    name: "Tsonga",
    nativeName: "Xitsonga",
  },
  {
    tag: "tt",
    name: "Tatar",
    nativeName: "татар",
  },
  {
    tag: "twq",
    name: "Tasawaq",
    nativeName: "Tasawaq senni",
  },
  {
    tag: "tyv",
    name: "Tuvinian",
    nativeName: "Тыва",
  },
  {
    tag: "tzm",
    name: "Central Atlas Tamazight",
    nativeName: "Tamaziɣt n laṭlaṣ",
  },
  {
    tag: "ug",
    name: "Uyghur",
    nativeName: "ئۇيغۇرچە",
  },
  {
    tag: "uk",
    name: "Ukrainian",
    nativeName: "Українська",
  },
  {
    tag: "ur",
    name: "Urdu",
    nativeName: "اردو",
  },
  {
    tag: "uz",
    name: "Uzbek",
    nativeName: "o‘zbek",
  },
  {
    tag: "vai",
    name: "Vai",
    nativeName: "ꕙꔤ",
  },
  {
    tag: "ve",
    name: "Venda",
    nativeName: "Tshivenḓa",
  },
  {
    tag: "vec",
    name: "Venetian",
    nativeName: "veneto",
  },
  {
    tag: "vi",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
  },
  {
    tag: "vmw",
    name: "Makhuwa",
    nativeName: "emakhuwa",
  },
  {
    tag: "vun",
    name: "Vunjo",
    nativeName: "Kyivunjo",
  },
  {
    tag: "wa",
    name: "Walloon",
    nativeName: "walon",
  },
  {
    tag: "wae",
    name: "Walser",
    nativeName: "Walser",
  },
  {
    tag: "wal",
    name: "Wolaytta",
    nativeName: "ወላይታቱ",
  },
  {
    tag: "wo",
    name: "Wolof",
    nativeName: "Wolof",
  },
  {
    tag: "xh",
    name: "Xhosa",
    nativeName: "IsiXhosa",
  },
  {
    tag: "xnr",
    name: "Kangri",
    nativeName: "कांगड़ी",
  },
  {
    tag: "xog",
    name: "Soga",
    nativeName: "Olusoga",
  },
  {
    tag: "yav",
    name: "Yangben",
    nativeName: "nuasue",
  },
  {
    tag: "yi",
    name: "Yiddish",
    nativeName: "ייִדיש",
  },
  {
    tag: "yo",
    name: "Yoruba",
    nativeName: "Èdè Yorùbá",
  },
  {
    tag: "yrl",
    name: "Nheengatu",
    nativeName: "Nheẽgatu",
  },
  {
    tag: "yue",
    name: "Cantonese",
    nativeName: "廣東話",
  },
  {
    tag: "za",
    name: "Zhuang",
    nativeName: "Vahcuengh",
  },
  {
    tag: "zgh",
    name: "Tamazight, Standard Moroccan",
    nativeName: "ⵜⴰⵎⴰⵣⵉⵖⵜ",
  },
  {
    tag: "zh",
    name: "Chinese",
    nativeName: "中文",
  },
  {
    tag: "zh-Hans",
    name: "Chinese, Simplified",
    nativeName: "简体中文",
  },
  {
    tag: "zh-Hant",
    name: "Chinese, Traditional",
    nativeName: "繁體中文",
  },
  {
    tag: "zu",
    name: "Zulu",
    nativeName: "isiZulu",
  },
];
