// SPDX-License-Identifier: MIT
/** Regenerate the fixed catalog after deliberately updating the bundled CLDR runtime. */
import { writeFile } from "node:fs/promises";
import { format } from "prettier";

const letters = "abcdefghijklmnopqrstuvwxyz";
const candidates: string[] = [];
for (const first of letters) {
  for (const second of letters) {
    candidates.push(first + second);
    for (const third of letters) candidates.push(first + second + third);
  }
}
candidates.push("en-GB", "en-US", "es-419", "pt-BR", "pt-PT", "zh-Hans", "zh-Hant");
const pluralLocales = Intl.PluralRules.supportedLocalesOf(candidates, { localeMatcher: "lookup" });
const displayLocales = Intl.DisplayNames.supportedLocalesOf(pluralLocales, {
  localeMatcher: "lookup",
});
const english = new Intl.DisplayNames("en", {
  type: "language",
  languageDisplay: "standard",
  fallback: "none",
});
const languages = [...new Set(displayLocales)]
  .flatMap((tag) => {
    const name = english.of(tag);
    const nativeName = new Intl.DisplayNames(tag, {
      type: "language",
      languageDisplay: "standard",
      fallback: "none",
    }).of(tag);
    return name && nativeName ? [{ tag, name, nativeName }] : [];
  })
  .sort((a, b) => a.tag.localeCompare(b.tag, "en"));
const source = `// SPDX-License-Identifier: MIT
// Generated by scripts/generate_language_catalog.ts; request choices stay identical on every host.
export const SUPPORTED_LANGUAGES: readonly { tag: string; name: string; nativeName: string }[] = ${JSON.stringify(languages, null, 2)};
`;
await writeFile(
  new URL("../packages/core/src/language_catalog.ts", import.meta.url),
  await format(source, { parser: "typescript", printWidth: 100 }),
);
console.log(`Wrote ${languages.length} supported languages.`);
